name: Build and Deploy Docs Guidelines
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install ubuntu Deps
        run: sudo apt-get install -y pandoc graphviz
      - name: Install python Deps
        run: |
          python -m pip install -U tox
          python -m pip install -r requirements-dev.txt
      - name: Build Docs
        run: tox -epy -- -j auto
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html # The folder the action should deploy.
